In [78]:
import numpy as np

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [79]:
a = np.arange(12, 24)

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [80]:
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(4, 3)
a4 = a.reshape(6, 2)
a5 = a.reshape(12, 1)

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [81]:
b1 = a.reshape(2, -1)
b2 = a.reshape(3, -1)
b3 = a.reshape(4, -1)
b4 = a.reshape(-1, 2)
b5 = a.reshape(-1, 1)

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [82]:
a.ndim == a.reshape(12, 1).ndim

False

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [83]:
a = np.random.randn(3, 4)
b = a.flatten()
a.size == b.size

True

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [84]:
a = np.arange(20, 0, -2)

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [85]:
b = np.arange(20, 0, -2).reshape(1, -1)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [86]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
print(v)
print(v.size)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
10


Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [87]:
a = np.arange(12)
A = a.reshape(4, 3)
print(A)

At = A.T
print(At)

B = A.dot(At)
print(B.size)

B_det = np.linalg.det(B)
print(B_det)

if B_det != 0:
    B_inv = np.linalg.inv(B_det)
    print(B_inv)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
16
0.0


Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [88]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [89]:
c = np.random.randn(16)
c

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004,
       -0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783,
       -0.56228753])

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [90]:
C = c.reshape(4, 4)
C

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753]])

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [91]:
D = B + (C * 10)

D_rank = np.linalg.matrix_rank(D)
print('D rank', D_rank)

D_det = np.linalg.det(D)
D_inv = np.linalg.inv(D)
D_inv

D rank 4


array([[ 0.29720511, -0.00032509,  0.0577031 , -0.08758856],
       [ 0.06723693, -0.02703394,  0.06811256, -0.04653751],
       [ 0.05021026,  0.06455969,  0.00094646, -0.03691049],
       [-0.09084592, -0.03300173, -0.0309639 ,  0.05395253]])

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [92]:
D_inv = np.where(D_inv > 0, 1, 0)

print(D_inv)

E = np.where(D_inv > 0, B, C)
print(E)

[[1 0 1 0]
 [1 0 1 0]
 [1 1 1 0]
 [0 0 0 1]]
[[ 5.00000000e+00 -1.38264301e-01  2.30000000e+01  1.52302986e+00]
 [ 1.40000000e+01 -2.34136957e-01  8.60000000e+01  7.67434729e-01]
 [ 2.30000000e+01  8.60000000e+01  1.49000000e+02 -4.65729754e-01]
 [ 2.41962272e-01 -1.91328024e+00 -1.72491783e+00  3.02000000e+02]]
